-- Seeding data for Table: pengalaman_profesi
DELETE FROM pengalaman_profesi;

INSERT INTO pengalaman_profesi (id, logo_url, paklaring, peran, tingkatan, perusahaan, periode, industri, deskripsi, spesialisasi, tugas_tanggung_jawab, ringkasan) VALUES
(
    'kerja-1',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-shansusdzar-indonesia.png',
    '',
    'Operational Manager',
    'Project Based',
    'PT Shansudza Indonesia',
    '{"masuk": "2025", "keluar": "Sekarang"}',
    'Manajemen Proyek & Operasional',
    'Memimpin operasional proyek mulai dari perencanaan, pengawasan pelaksanaan, pengendalian kualitas, hingga koordinasi dengan klien. Berhasil menjaga tingkat penyelesaian proyek tepat waktu sekitar 96%, meningkatkan efisiensi proses kerja sekitar 20%, serta mempertahankan standar kualitas operasional secara konsisten.',
    '["Operational Management", "Project Management", "Quality Assurance", "Client Management", "Process Optimization", "Team Leadership"]',
    '["Perencanaan Operasional: Menyusun rencana kerja proyek dengan tingkat kesiapan sekitar 95% sebelum pelaksanaan.", "Pengawasan Proyek: Memastikan progres proyek berjalan sesuai timeline dengan tingkat ketepatan sekitar 96%.", "Quality Control: Mengawasi kualitas pekerjaan sehingga tingkat kesesuaian terhadap standar mencapai sekitar 98%.", "Koordinasi Klien: Menjalin komunikasi aktif dengan klien untuk memastikan kebutuhan proyek terpenuhi secara optimal.", "Pengembangan Tim: Mengarahkan dan mengevaluasi tim operasional sehingga produktivitas meningkat sekitar 18%."]',
    '[{"pekerjaan": "Ketepatan Penyelesaian Proyek", "persentase": 96}, {"pekerjaan": "Kepatuhan Standar Kualitas", "persentase": 98}, {"pekerjaan": "Efisiensi Operasional", "persentase": 20}, {"pekerjaan": "Produktivitas Tim", "persentase": 18}]'
),
(
    'kerja-2',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-gmg.png',
    '/gambar/paklaring/gmg.webp',
    'Operational Manager',
    'Project Based',
    'PT Galaksi Mitra Gemilang',
    '{"masuk": "2024", "keluar": "2025"}',
    'Logistik & Operasional',
    'Mengelola operasional perusahaan, mengawasi pelaksanaan pekerjaan, serta memastikan seluruh aktivitas berjalan sesuai target. Berhasil meningkatkan efisiensi operasional sekitar 22% and menjaga penyelesaian pekerjaan tepat waktu hingga 95%.',
    '["Operational Management", "Project Monitoring", "SOP Implementation", "Team Leadership", "Process Improvement", "Quality Control"]',
    '["Manajemen Operasional: Mengendalikan aktivitas operasional dengan tingkat pencapaian target sekitar 95%.", "Pengawasan Pekerjaan: Memastikan seluruh pekerjaan sesuai SOP dengan kepatuhan sekitar 98%.", "Koordinasi Tim: Mengoptimalkan pembagian tugas sehingga efisiensi kerja meningkat sekitar 22%.", "Monitoring Target: Mengawasi progres pekerjaan melalui evaluasi berkala.", "Peningkatan Proses: Mengembangkan proses kerja agar lebih efektif dan efisien."]',
    '[{"pekerjaan": "Efisiensi Operasional", "persentase": 22}, {"pekerjaan": "Ketepatan Penyelesaian", "persentase": 95}, {"pekerjaan": "Kepatuhan SOP", "persentase": 98}, {"pekerjaan": "Produktivitas Tim", "persentase": 18}]'
),
(
    'kerja-4',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/konika-minolta.png',
    '',
    'Account Manager',
    'Project Based',
    'PT Perdana Jatiputra',
    '{"masuk": "2024", "keluar": "2024"}',
    'Distribusi & Penjualan B2B',
    'Mengelola hubungan dengan klien, penyusunan penawaran, koordinasi proyek, serta pengembangan peluang bisnis. Berkontribusi meningkatkan retensi klien sekitar 18% and mempercepat proses koordinasi proyek hingga 20%.',
    '["Account Management", "Client Relationship", "Business Development", "Proposal Management", "Project Coordination", "Negotiation"]',
    '["Hubungan Klien: Menjaga komunikasi dengan klien sehingga tingkat kepuasan mencapai sekitar 90%.", "Penyusunan Penawaran: Menyiapkan proposal dan penawaran sesuai kebutuhan klien dengan ketepatan sekitar 98%.", "Koordinasi Proyek: Menghubungkan kebutuhan klien dengan tim internal sehingga proses kerja lebih efisien sekitar 20%.", "Administrasi Penjualan: Mengelola dokumen penjualan secara lengkap dan tepat waktu.", "Pengembangan Bisnis: Mengidentifikasi peluang kerja sama baru untuk mendukung pertumbuhan perusahaan."]',
    '[{"pekerjaan": "Retensi Klien", "persentase": 18}, {"pekerjaan": "Efisiensi Koordinasi", "persentase": 20}, {"pekerjaan": "Akurasi Proposal", "persentase": 98}, {"pekerjaan": "Kepuasan Klien", "persentase": 90}]'
),
(
    'kerja-5',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/vanysongket.png',
    '',
    'Social Media Manager',
    'Project Based',
    'PT Vany''s Group',
    '{"masuk": "2023", "keluar": "2024"}',
    'Agensi Media & Periklanan',
    'Mengelola seluruh aktivitas media sosial perusahaan mulai dari perencanaan konten, iklan digital, hingga analisis performa. Berhasil meningkatkan engagement sekitar 35%, jangkauan konten 40%, dan konsistensi publikasi hingga 100%.',
    '["Social Media Strategy", "Content Marketing", "Meta Ads", "Performance Analytics", "Branding", "Campaign Optimization"]',
    '["Manajemen Media Sosial: Mengelola seluruh platform media sosial dengan konsistensi publikasi mencapai 100%.", "Strategi Konten: Menyusun konten yang meningkatkan jangkauan organik sekitar 40%.", "Digital Advertising: Mengoptimalkan iklan digital dengan peningkatan performa kampanye sekitar 25%.", "Monitoring Analytics: Mengevaluasi insight media sosial untuk meningkatkan engagement sekitar 35%.", "Pengembangan Branding: Menjaga citra perusahaan melalui komunikasi visual yang konsisten."]',
    '[{"pekerjaan": "Engagement", "persentase": 35}, {"pekerjaan": "Reach Konten", "persentase": 40}, {"pekerjaan": "Efektivitas Iklan", "persentase": 25}, {"pekerjaan": "Konsistensi Publikasi", "persentase": 100}]'
),
(
    'kerja-6',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/hokage.png',
    '/gambar/paklaring/multisejahtera.webp',
    'Marketing Communication Manager',
    'Project Based',
    'CV Multi Sejahtera',
    '{"masuk": "2023", "keluar": "2023"}',
    'Perdagangan & Ritel',
    'Memimpin aktivitas komunikasi pemasaran perusahaan mulai dari penyusunan strategi, koordinasi promosi, hingga evaluasi performa kampanye. Berhasil meningkatkan efektivitas kampanye sekitar 28% and memperkuat konsistensi branding perusahaan.',
    '["Marketing Strategy", "Team Coordination", "Branding", "Campaign Management", "Performance Analysis", "Business Communication"]',
    '["Strategi Pemasaran: Menyusun strategi pemasaran yang meningkatkan efektivitas kampanye hingga sekitar 28%.", "Koordinasi Tim: Mengarahkan tim pemasaran sehingga target pekerjaan tercapai lebih konsisten sekitar 95%.", "Pengelolaan Branding: Menjaga konsistensi identitas perusahaan di seluruh media promosi.", "Monitoring Kinerja: Mengevaluasi performa kampanye menggunakan data dan KPI pemasaran.", "Pelaporan Manajemen: Menyusun laporan perkembangan pemasaran sebagai dasar pengambilan keputusan."]',
    '[{"pekerjaan": "Efektivitas Kampanye", "persentase": 28}, {"pekerjaan": "Konsistensi Target Tim", "persentase": 95}, {"pekerjaan": "Peningkatan Brand Exposure", "persentase": 22}, {"pekerjaan": "Ketepatan Evaluasi", "persentase": 98}]'
),
(
    'kerja-7',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/jayabaru.png',
    '/gambar/paklaring/jayabaru.webp',
    'Marketing Communication',
    'Project Based',
    'CV Jayabaru',
    '{"masuk": "2023", "keluar": "2023"}',
    'Pemasaran & Distribusi',
    'Mengembangkan strategi komunikasi pemasaran melalui media sosial dan berbagai materi promosi perusahaan. Berkontribusi meningkatkan jangkauan digital sekitar 30% serta meningkatkan interaksi audiens rata-rata 20% melalui penyusunan konten yang lebih terarah.',
    '["Marketing Communication", "Content Planning", "Branding", "Copywriting", "Social Media", "Promotion Strategy"]',
    '["Perencanaan Konten: Menyusun kalender konten yang meningkatkan konsistensi publikasi hingga 100% sesuai jadwal.", "Brand Communication: Mengembangkan materi komunikasi untuk memperkuat identitas merek dengan peningkatan awareness sekitar 25%.", "Promosi Digital: Membuat materi promosi yang membantu meningkatkan engagement sekitar 20%.", "Koordinasi Tim: Berkolaborasi dengan berbagai divisi agar proses promosi berjalan efektif dengan efisiensi waktu sekitar 15%.", "Evaluasi Kampanye: Melakukan analisis performa kampanye sebagai dasar perbaikan strategi berikutnya."]',
    '[{"pekerjaan": "Peningkatan Engagement", "persentase": 20}, {"pekerjaan": "Brand Awareness", "persentase": 25}, {"pekerjaan": "Jangkauan Konten", "persentase": 30}, {"pekerjaan": "Konsistensi Publikasi", "persentase": 100}]'
),
(
    'exp-11',
    '/gambar/bpspams.png',
    '/gambar/paklaring/bpspams.webp',
    'Administrasi Dan Keuangan',
    'Staff',
    'BPSPAMS',
    '{"masuk": "2022", "keluar": "2023"}',
    'Utilitas & Pengelolaan Air',
    'Mengelola seluruh administrasi, pencatatan keuangan, pelaporan berkala, serta pelayanan administrasi pelanggan untuk BPSPAMS skala desa.',
    '["Administrasi Keuangan", "Pencatatan Transaksi", "Pelaporan Keuangan", "Pelayanan Pelanggan", "Pengarsipan Dokumen"]',
    '["Pencatatan Keuangan: Menyusun laporan arus kas harian dan mingguan dengan tingkat ketelitian tinggi.", "Administrasi Pelanggan: Mengelola pencatatan administrasi penggunaan layanan air pelanggan desa.", "Arsip Dokumen: Mengatur pengarsipan dokumen transaksi dan tagihan agar mudah diakses saat audit internal."]',
    '[{"pekerjaan": "Administrasi Keuangan", "persentase": 50}, {"pekerjaan": "Pelayanan Pelanggan", "persentase": 30}, {"pekerjaan": "Pengarsipan Dokumen", "persentase": 20}]'
),
(
    'exp-7',
    '/gambar/tirtaabadiutama.png',
    '',
    'Field Marketing Officer',
    'Officer / Staff',
    'PT TIRTA ABADI UTAMA',
    '{"masuk": "2020", "keluar": "2021"}',
    'FMCG (Fast Moving Consumer Goods)',
    'Bertanggung jawab mengelola distribusi produk, monitoring stok, serta memastikan ketersediaan produk di area penjualan. Mendukung peningkatan efektivitas distribusi hingga sekitar 18%, menjaga tingkat ketersediaan produk rata-rata di atas 95%, serta memperkuat hubungan kerja sama dengan outlet dan distributor.',
    '["Field Marketing", "Distribution Management", "Stock Monitoring", "Sales Support", "Area Coverage", "Trade Marketing"]',
    '["Monitoring Distribusi: Mengawasi proses distribusi produk agar tingkat ketersediaan mencapai sekitar 95% di seluruh area.", "Manajemen Stok: Mengontrol stok produk untuk mengurangi potensi kekosongan barang hingga sekitar 20%.", "Hubungan Mitra: Menjalin komunikasi aktif dengan distributor dan outlet untuk meningkatkan efektivitas kerja sama sekitar 15%.", "Analisis Lapangan: Melakukan evaluasi kondisi pasar dan kompetitor sebagai dasar pengambilan keputusan pemasaran.", "Pelaporan: Menyusun laporan penjualan dan distribusi secara berkala dengan tingkat ketepatan data sekitar 98%."]',
    '[{"pekerjaan": "Ketersediaan Produk", "persentase": 95}, {"pekerjaan": "Efektivitas Distribusi", "persentase": 18}, {"pekerjaan": "Pengurangan Stock Out", "persentase": 20}, {"pekerjaan": "Akurasi Laporan", "persentase": 98}]'
),
(
    'exp-8',
    '/gambar/bjb.png',
    '',
    'PKL / Magang',
    'Intern / Internship',
    'PT Bank Pembangunan Daerah Jawa Barat dan Banten, Tbk (Bank bjb)',
    '{"masuk": "2019", "keluar": "2019"}',
    'Perbankan & Keuangan',
    'Melaksanakan program Praktik Kerja Lapangan pada unit operasional perbankan dengan berfokus pada administrasi dokumen, pelayanan nasabah, serta pengelolaan data transaksi. Berhasil menyelesaikan sekitar 95% pekerjaan administrasi tepat waktu serta membantu meningkatkan ketelitian pengarsipan dokumen hingga sekitar 20% melalui proses pencatatan yang lebih rapi.',
    '["Administrasi Perbankan", "Pengarsipan Dokumen", "Input Data", "Pelayanan Nasabah", "Microsoft Office", "Administrasi Operasional"]',
    '["Administrasi Dokumen: Mengelola, menyusun, dan mengarsipkan dokumen operasional dengan tingkat akurasi sekitar 98%.", "Input Data: Melakukan pencatatan data transaksi dan administrasi harian dengan ketepatan input sekitar 97%.", "Pelayanan Nasabah: Membantu proses pelayanan serta memberikan informasi dasar kepada nasabah dengan tingkat kepuasan layanan yang baik.", "Koordinasi Internal: Berkoordinasi dengan staf operasional untuk memastikan proses administrasi berjalan lancar dan sesuai prosedur.", "Kepatuhan SOP: Menjalankan seluruh pekerjaan sesuai standar operasional perusahaan dengan kepatuhan sekitar 100% terhadap prosedur yang diberikan."]',
    '[{"pekerjaan": "Ketepatan Administrasi", "persentase": 98}, {"pekerjaan": "Penyelesaian Tugas Tepat Waktu", "persentase": 95}, {"pekerjaan": "Efisiensi Pengarsipan", "persentase": 20}, {"pekerjaan": "Akurasi Input Data", "persentase": 97}]'
);
