-- Seeding data for Table: cover_letter_templates
DROP TABLE IF EXISTS cover_letter_templates;
CREATE TABLE IF NOT EXISTS cover_letter_templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    body TEXT NOT NULL,
    bahasa TEXT,
    rekomendasi TEXT
);

INSERT INTO cover_letter_templates (id, name, body, bahasa, rekomendasi) VALUES
('tpl-1', 'Umum', 'Saya merupakan lulusan **Sarjana Manajemen dari STIE Wikara** dengan portofolio pengalaman kerja yang solid di bidang **operasional ritel dan manajemen proyek**. Portofolio profesional saya mencakup peran strategis dalam mengelola efisiensi alur kerja di **Lingua / Tirta Abadi Utama** serta penyelesaian proyek distribusi sumber daya pada program **BPSPAMS**. Didukung dengan kepemimpinan kuat selaku mantan **Presiden Mahasiswa** serta gelar **Duta GenRe Kabupaten Purwakarta**, saya terbiasa mengoordinasikan tim lintas divisi dan membangun kemitraan strategis.

Saya memiliki daya adaptasi tinggi, etos kerja disiplin, dan kemampuan public speaking yang mumpuni. Saya sangat antusias untuk mengaplikasikan rekam jejak manajerial ini untuk mendukung operasional dan pencapaian target **[Perusahaan]** sebagai **[Posisi]**.', 'Indonesia', '["HRD", "PR", "Manajemen"]'),
('tpl-2', 'General', 'I am a **Bachelor of Management from STIE Wikara** with a robust work portfolio in **retail operations and project management**. My professional background includes managing operational workflows at **Lingua / Tirta Abadi Utama** and resource coordination within the **BPSPAMS project**. Combined with my leadership experience as the **President of the Student Executive Board (Presma)** and my achievement as **Duta GenRe Kabupaten Purwakarta**, I excel in cross-functional coordination and strategic partnerships.

I possess strong adaptability, exceptional communication skills, and a result-oriented mindset. I am highly motivated to leverage my practical experience and leadership track record to contribute to **[Perusahaan]** as a **[Posisi]**.', 'Inggris', '["HRD", "PR", "Management"]'),
('tpl-3', 'Fokus Kepemimpinan, Akademis & Prestasi', 'Sebagai lulusan **Sarjana Manajemen dari STIE Wikara** yang memegang **Sertifikat Kompetensi Kepemimpinan & Public Speaking**, perjalanan karir saya dibentuk oleh jiwa kepemimpinan yang matang dan prestasi nyata. Saya dipercaya memimpin organisasi kemahasiswaan tertinggi sebagai **Presiden Mahasiswa STIE Wikara** dan mengoordinasikan aksi daerah bersama **Aliansi BEM Purwakarta**. Prestasi saya sebagai **Duta GenRe Kabupaten Purwakarta** merefleksikan keahlian komunikasi persuasif dan diplomasi yang kuat, yang juga saya terapkan saat mengoptimalkan tim operasional di **Lingua / Tirta Abadi Utama** dan **BPSPAMS**.

Saya memiliki kemampuan pemecahan masalah yang analitis dan mentalitas yang berorientasi pada prestasi. Saya siap membawa dedikasi terbaik ini untuk mendukung pertumbuhan **[Perusahaan]** pada posisi **[Posisi]**.', 'Indonesia', '["Kepemimpinan", "Akademis", "Prestasi"]'),
('tpl-4', 'Focus on Academic Excellence, Leadership & Awards', 'As a **Bachelor of Management from STIE Wikara** holding **Leadership & Public Speaking Certificates**, my professional journey is anchored in high-impact leadership and recognized excellence. I served as the **President of the Student Executive Board (Presma)** and regional coordinator for the **Purwakarta Student Alliance**. My achievement as **Duta GenRe Kabupaten Purwakarta** highlights my ability to influence and build alliances, which I have successfully translated into operational achievements at **Lingua / Tirta Abadi Utama** and **BPSPAMS**.

With a strong foundation in strategic management, outstanding communication, and a history of awards, I am fully prepared to excel as a **[Posisi]** at **[Perusahaan]**.', 'Inggris', '["Academic", "Leadership", "Awards"]'),
('tpl-5', 'Fokus Pengalaman Kerja & Operasional Ritel', 'Portofolio profesional saya berfokus pada **manajemen operasional ritel dan efisiensi kerja**. Saya memiliki pengalaman langsung mengelola rantai pasok dan pelayanan pelanggan di **Lingua / Tirta Abadi Utama**, serta memimpin administrasi dan pelaporan keuangan pada proyek lingkungan **BPSPAMS**. Melalui pengalaman ini, didukung kompetensi manajerial dari studi **Sarjana Manajemen STIE Wikara**, saya terbukti mampu mereduksi hambatan operasional dan meningkatkan kepuasan mitra kerja secara signifikan.

Dengan dukungan sertifikasi kompetensi di bidang **Bisnis dan Digital**, saya siap menerapkan strategi operasional yang lincah dan berorientasi data untuk mengoptimalkan kinerja divisi **[Posisi]** di **[Perusahaan]**.', 'Indonesia', '["Pengalaman Kerja", "Ritel", "Operasional"]'),
('tpl-6', 'Focus on Work Experience & Retail Operations', 'My professional portfolio is centered on **retail operations management and workflow optimization**. I have hands-on experience managing supply chain logistics and customer relations at **Lingua / Tirta Abadi Utama**, alongside administering project logistics for the **BPSPAMS program**. Guided by my business education in **Bachelor of Management from STIE Wikara**, I have a proven track record of reducing operational bottlenecks and driving partner satisfaction.

Holding a **Digital Business Competency Certificate**, I am fully equipped to bring agile, data-driven operational solutions to support the **[Posisi]** role at **[Perusahaan]**.', 'Inggris', '["Work Experience", "Retail", "Operations"]'),
('tpl-7', 'Management Trainee / Graduate Leader Program', 'Sebagai lulusan **Sarjana Manajemen dari STIE Wikara** dengan jiwa kepemimpinan tinggi selaku mantan **Presiden Mahasiswa**, saya sangat berambisi untuk bergabung dalam program **Management Trainee** di **[Perusahaan]**. Latar belakang akademis saya diperkuat oleh pengalaman lapangan mengelola operasional ritel di **Lingua / Tirta Abadi Utama** serta administrasi proyek **BPSPAMS**, yang membuktikan bahwa saya tidak hanya menguasai teori, tetapi juga andal dalam eksekusi taktis.

Dengan kepemilikan **Sertifikat Kompetensi Bisnis, Digital, dan Kepemimpinan**, saya memiliki kegesitan belajar (learning agility) yang tinggi untuk ditempatkan lintas divisi. Saya siap mendedikasikan potensi terbaik saya untuk tumbuh dan berkontribusi jangka panjang bagi **[Perusahaan]** sebagai **[Posisi]**.', 'Indonesia', '["MT", "Graduate Leader"]'),
('tpl-8', 'Management Trainee / Future Leaders Program', 'As a **Bachelor of Management from STIE Wikara** with stellar leadership credentials as the former **President of the Student Executive Board (Presma)**, I am highly driven to join the **Management Trainee program** at **[Perusahaan]**. My academic excellence is balanced by solid hands-on experience in retail operations at **Lingua / Tirta Abadi Utama** and administrative governance at **BPSPAMS**, proving my capability to transition smoothly from strategy to execution.

Armed with **Leadership & Digital Business certificates**, I possess high learning agility and cross-functional adaptability. I am eager to contribute fresh strategic perspectives and a strong work ethic to **[Perusahaan]** as a **[Posisi]**.', 'Inggris', '["MT", "Future Leaders"]'),
('tpl-9', 'Hubungan Masyarakat, Publik & Kemitraan', 'Dengan kombinasi keahlian sebagai **Duta GenRe Kabupaten Purwakarta** dan pemegang **Sertifikat Kompetensi Public Speaking**, saya melamar untuk posisi **[Posisi]** di **[Perusahaan]**. Keahlian komunikasi strategis saya terasah nyata melalui peran eksternal di **Aliansi BEM Purwakarta** serta koordinasi kemitraan publik pada proyek **BPSPAMS**. Saya mahir dalam mengelola pesan komunikasi publik, menjalin relasi media, serta membangun citra positif organisasi.

Didukung oleh landasan keilmuan **Sarjana Manajemen dari STIE Wikara**, saya memiliki pendekatan yang sistematis dan berorientasi bisnis dalam merancang strategi kehumasan. Saya yakin dapat memperkuat reputasi dan hubungan kemitraan strategis **[Perusahaan]**.', 'Indonesia', '["Humas", "Public Relations", "PR"]'),
('tpl-10', 'Public Relations, Communication & Partnerships', 'Leveraging my background as the **Duta GenRe (Ambassador) of Purwakarta Regency** and my **Public Speaking Competency Certificate**, I am writing to apply for the **[Posisi]** role at **[Perusahaan]**. My communication skills were honed through managing external stakeholder relations for the **Purwakarta Student Alliance** and coordinating public partnerships for **BPSPAMS**. I excel in public speaking, message crafting, and building long-term organizational trust.

With a structured business mindset from my **Bachelor of Management from STIE Wikara**, I bring a strategic approach to public relations. I am highly confident in my ability to enhance stakeholder engagement and public trust for **[Perusahaan]**.', 'Inggris', '["PR", "Communication", "Partnerships"]'),
('tpl-11', 'Administrasi Operasional & Manajemen Kantor', 'Sebagai lulusan **Sarjana Manajemen dari STIE Wikara** dengan penguasaan mendalam dalam tata kelola administrasi, saya bermaksud mengajukan diri untuk posisi **[Posisi]** di **[Perusahaan]**. Pengalaman saya memimpin administrasi kegiatan mahasiswa selaku **Presiden Mahasiswa** serta mengelola pelaporan dan logistik keuangan pada program **BPSPAMS** menjamin ketelitian tinggi, keteraturan berkas, dan efisiensi koordinasi harian.

Didukung oleh **Sertifikat Kompetensi Akademik**, saya sangat terbiasa menggunakan instrumen digital untuk manajemen data operasional. Saya berkomitmen penuh untuk menjaga kelancaran operasional harian kantor di **[Perusahaan]** dengan etos kerja yang disiplin dan andal.', 'Indonesia', '["Administrasi", "Office Management"]'),
('tpl-12', 'Office Administration & Operational Support', 'With a solid academic background in **Bachelor of Management from STIE Wikara** and extensive organizational governance experience, I am applying for the **[Posisi]** role at **[Perusahaan]**. My expertise in document control, budget tracking, and scheduling was developed during my tenure as **President of the Student Executive Board** and through handling operational logs for **BPSPAMS** and **Lingua / Tirta Abadi Utama**.

Equipped with an **Academic Competency Certificate**, I am highly proficient in digital administration tools and administrative database management. I am committed to supporting the daily office efficiency and operational workflow of **[Perusahaan]**.', 'Inggris', '["Office Administration", "Operational Support"]'),
('tpl-13', 'Fokus Digital Marketing & Pemasaran', 'Sebagai lulusan **Sarjana Manajemen dari STIE Wikara** yang memiliki minat besar dan pengalaman lapangan di bidang pemasaran, saya mengajukan diri untuk posisi **[Posisi]** di **[Perusahaan]**. Berbekal pengalaman dalam pemasaran lapangan dan pemahaman kuat terhadap perilaku konsumen, saya mahir dalam merancang strategi akuisisi audiens, membangun kesadaran merek (brand awareness), serta mengoptimalkan kampanye yang berorientasi pada data dan hasil nyata.

Dengan sertifikasi kompetensi di bidang **Bisnis dan Digital**, pemahaman manajerial yang solid, serta kreativitas yang terasah melalui kepemimpinan kemahasiswaan, saya siap membantu meningkatkan metrik konversi dan visibilitas digital **[Perusahaan]**.', 'Indonesia', '["Digital Marketing", "Pemasaran"]'),
('tpl-14', 'Focus on Digital Marketing & Growth', 'As a **Bachelor of Management from STIE Wikara** with a profound passion and hands-on experience in marketing operations, I am writing to express my interest in the **[Posisi]** role at **[Perusahaan]**. Equipped with a robust background in field marketing and consumer behavior analysis, I am highly capable of designing audience acquisition strategies, driving brand awareness, and optimizing data-driven campaigns for tangible growth.

Holding a **Digital Business Competency Certificate** alongside a solid managerial foundation and creativity honed through leadership roles, I am eager to contribute to boosting digital visibility and conversion metrics for **[Perusahaan]**.', 'Inggris', '["Digital Marketing", "Growth"]');
