-- Seeding data for Table: pengalaman_kerjasama
DELETE FROM pengalaman_kerjasama;

INSERT INTO pengalaman_kerjasama (id, partner, peran, proyek, periode, mulai, selesai, bidang, deskripsi, tujuan, dampak, logo_url, paklaring) VALUES
(
    'collab-6',
    'Melin Parfum',
    'Strategic Partner / Founder',
    'Pembangunan Brand & Strategi Penjualan Ritel',
    'Tahun Berdiri - Sekarang',
    '2023',
    'Sekarang',
    'Ritel & Kosmetik',
    'Kemitraan pendiri dalam merintis, membangun model bisnis, merancang identitas merek, dan mengeksekusi strategi pemasaran digital parfum.',
    '["Merancang identitas brand parfum yang memiliki daya pikat tinggi di pasar lokal.", "Menyusun saluran pemasaran online dan offline yang efektif dan berkelanjutan."]',
    '[{"indikator": "Kemandirian rantai pasok produk", "persentase": 90}, {"indikator": "Retensi pelanggan ritel digital", "persentase": 88}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/melin-parfum.png',
    ''
),
(
    'collab-7',
    'Wood Street',
    'Strategic Partner / Founder',
    'Manajemen Bisnis & Operasional Outlet Kuliner',
    'Tahun Berdiri - Sekarang',
    '2022',
    'Sekarang',
    'F&B / Ritel',
    'Kemitraan operasional dalam mengonsep, mengelola, serta mengembangkan operasional harian outlet kuliner Wood Street secara menyeluruh.',
    '["Membangun manajemen operasional outlet yang efisien and mengutamakan kualitas produk.", "Meningkatkan daya tarik outlet melalui aktivitas pemasaran kreatif di wilayah target."]',
    '[{"indikator": "Kerapihan tata kelola F&B", "persentase": 95}, {"indikator": "Kenaikan arus kunjungan pelanggan", "persentase": 30}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/worldstreet.png',
    ''
),
(
    'collab-8',
    'Alin Labs',
    'Strategic Partner / Founder',
    'Penyusunan Solusi & Layanan Teknologi Digital',
    'Tahun Berdiri - Sekarang',
    '2022',
    'Sekarang',
    'Teknologi / Layanan Digital',
    'Kemitraan teknologi dalam penyusunan produk, penyediaan konsultansi, dan pengerjaan proyek-proyek inovasi digital untuk klien.',
    '["Melahirkan solusi rekayasa perangkat lunak dan layanan digital yang handal.", "Mengelola siklus pengerjaan proyek teknologi informasi secara profesional dan akurat."]',
    '[{"indikator": "Peluncuran produk digital UMKM", "persentase": 100}, {"indikator": "Reputasi mitra pengembang", "persentase": 96}]',
    'https://www.alinlabs.biz.id/gambar/logo-icon-color.png',
    ''
),
(
    'collab-5',
    'Lingua First',
    'Kemitraan Operasional (COO)',
    'Manajemen Mutu & Optimalisasi Operasional Pendidikan',
    '2024 - 2025',
    '2024',
    '2025',
    'Pendidikan & Pelatihan Bahasa',
    'Kolaborasi kepemimpinan operasional untuk memimpin, menata, dan mengoptimalkan seluruh aktivitas belajar mengajar harian, serta standarisasi kualitas mutu layanan.',
    '["Mengoptimalkan efisiensi operasional kursus bahasa dan koordinasi staf pengajar.", "Memastikan konsistensi standar mutu akademik untuk mempertahankan loyalitas siswa."]',
    '[{"indikator": "Efisiensi penjadwalan & koordinasi", "persentase": 25}, {"indikator": "Kepuasan layanan siswa", "persentase": 92}]',
    '/gambar/lingua.png',
    ''
),
(
    'collab-2',
    'STIE Wikara',
    'Konsultan Digital Marketing',
    'Social Media Branding & Awareness Kampus',
    '2024',
    '2024',
    '2024',
    'Pendidikan Tinggi',
    'Kemitraan dalam rangka perancangan strategi pemasaran digital dan sosial media guna memperkuat brand awareness STIE Wikara sebagai institusi pendidikan pilihan.',
    '["Meningkatkan jangkauan informasi penerimaan mahasiswa baru.", "Membangun citra kampus yang modern dan interaktif di media sosial."]',
    '[{"indikator": "Peningkatan audiens organik", "persentase": 75}, {"indikator": "Efektivitas kampanye promosi digital", "persentase": 80}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/stiewikara.png',
    ''
),
(
    'collab-4',
    'Pesantren Minnatul Huda',
    'Sistem Integrator / Developer',
    'Digitalisasi Sistem & Website Informasi Pesantren',
    '2023 - 2024',
    '2023',
    '2024',
    'Pendidikan & Sosial Keagamaan',
    'Kerjasama pengembangan platform digital berupa website resmi dan aplikasi manajemen internal untuk mendukung proses digitalisasi di lingkungan pesantren.',
    '["Menyediakan pusat informasi publik terpadu mengenai kegiatan pesantren.", "Modernisasi administrasi santri dan sistem informasi internal pesantren."]',
    '[{"indikator": "Aksesibilitas informasi publik", "persentase": 95}, {"indikator": "Efisiensi administrasi internal", "persentase": 85}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/minnatulhuda.png',
    ''
),
(
    'collab-4-2',
    'Pesantren Miftahul Huda',
    'Sistem Integrator / Developer',
    'Digitalisasi Sistem & Website Informasi Pesantren',
    '2023 - 2024',
    '2023',
    '2024',
    'Pendidikan & Sosial Keagamaan',
    'Kerjasama pengembangan platform digital berupa website resmi dan aplikasi manajemen internal untuk mendukung proses digitalisasi di lingkungan pesantren.',
    '["Menyediakan pusat informasi publik terpadu mengenai kegiatan pesantren.", "Modernisasi administrasi santri dan sistem informasi internal pesantren."]',
    '[{"indikator": "Aksesibilitas informasi publik", "persentase": 95}, {"indikator": "Efisiensi administrasi internal", "persentase": 85}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/miftahulhuda.png',
    ''
),
(
    'collab-3',
    'PT. Sentral Informatika, Tbk',
    'Professional Presentation Designer',
    'Penyusunan Presentasi Bisnis Tahunan',
    '2023 - 2024',
    '2023',
    '2024',
    'Teknologi & Informasi',
    'Kerjasama profesional dalam mendesain, memformulasikan konsep, dan menyusun materi presentasi laporan tahunan serta prospek bisnis korporat.',
    '["Menyampaikan performa bisnis perusahaan secara visual yang jernih dan profesional.", "Memastikan struktur materi presentasi selaras dengan visi korporat kepada stakeholder."]',
    '[{"indikator": "Akurasi & standar visual laporan", "persentase": 98}, {"indikator": "Pemahaman pesan bagi manajemen", "persentase": 90}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-sentral-informatika.png',
    ''
),
(
    'collab-1',
    'PT. Tiens Ambefit',
    'Mitra Kerjasama Konten',
    'Iklan Promosi Produk Kesehatan',
    '2024',
    '2024',
    '2024',
    'Kesehatan & Kebugaran',
    'Kerjasama strategis dalam perancangan dan produksi konten iklan promosi multimedia kreatif untuk jajaran produk kesehatan unggulan perusahaan.',
    '["Membuat visual promosi produk kesehatan yang menarik minat audiens.", "Mengoptimalkan digital marketing melalui konten video pendek di media sosial."]',
    '[{"indikator": "Peningkatan interaksi (engagement) digital", "persentase": 85}, {"indikator": "Materi periklanan berkualitas tinggi", "persentase": 95}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-tiensherba.png',
    ''
),
(
    'collab-9',
    'PT Anugrah Dwi Tunggal',
    'Mitra Kerjasama Konten',
    'Penyusunan Konten dan Manajemen Sosial Media',
    '2024',
    '2024',
    '2024',
    'Sosial Media & E-Commerce',
    'Kerjasama dalam pembuatan dan pengelolaan konten pemasaran di berbagai platform e-commerce dan sosial media.',
    '["Meningkatkan penjualan produk melalui konten yang menarik.", "Meningkatkan brand awareness di platform sosial media dan e-commerce."]',
    '[{"indikator": "Peningkatan engagement media sosial", "persentase": 85}, {"indikator": "Pertumbuhan transaksi penjualan online", "persentase": 70}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-adt.png',
    ''
),
(
    'collab-10',
    'PT Katisolusindo',
    'Mitra Kerjasama Konten',
    'Penyusunan Konten dan Manajemen Sosial Media',
    '2024',
    '2024',
    '2024',
    'Sosial Media & E-Commerce',
    'Kerjasama dalam pembuatan dan pengelolaan konten pemasaran di berbagai platform e-commerce dan sosial media.',
    '["Meningkatkan penjualan produk melalui konten yang menarik.", "Meningkatkan brand awareness di platform sosial media dan e-commerce."]',
    '[{"indikator": "Peningkatan engagement media sosial", "persentase": 85}, {"indikator": "Pertumbuhan transaksi penjualan online", "persentase": 70}]',
    'https://raw.githubusercontent.com/alinlabs/alinlabs-data/main/gambar/logo-klien/pt-katisolusindo.png',
    ''
);
